---
- name: Install coturn
  apt: name=coturn state=latest update_cache=yes

- name: Create turnserver config directory
  file: path=/opt/turnserver state=directory

- name: Install turnserver balancer config
  template: src=turnserver-balancer.conf dest=/opt/turnserver/turnserver-balancer.conf

- name: Install turnserver balancer service file
  template: src=turnserver-balancer.service dest=/etc/systemd/system/turnserver-balancer.service

- name: reload systemd
  command: systemctl daemon-reload

- name: start turnserver balancer
  service: name=turnserver-balancer state=started
